version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:22"
      timezone: "Asia/Calcutta"
